export const IPC = {
  configGet: "config:get",
  configSave: "config:save",
  configClear: "config:clear",
  sessions: "api:sessions",
  queue: "api:queue",
  decisions: "api:decisions",
  resolve: "api:resolve",
  snooze: "api:snooze",
  pin: "api:pin",
  streamEvent: "stream:event",
  instruct: "api:instruct",
  mode: "api:mode",
  workspaceGet: "api:workspace:get",
  workspaceSave: "api:workspace:save",
  workspaceGetSshHost: "api:workspace:sshhost:get",
  workspaceSetSshHost: "api:workspace:sshhost:set",
  workspaceIsLocal: "api:workspace:islocal",
} as const;
